language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer selfupdate
  - composer install

script: phpunit --coverage-text

notifications:
  email:
    recipients:
      - wolters.fl@gmail.com
    on_success: change
    on_failure: always
